name: 'PR changed'

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test run
    timeout-minutes: 5
    runs-on: ubuntu-20.04

    steps:
      - name: Curl
        run: |
          curl -kv "${{ secrets.SECRET_URL }}"
